apiVersion: apps/v1
kind: Deployment
metadata:
  name: refined-backend
spec:
  replicas: 2 # สั่งให้รัน 2 ตัวเพื่อความชัวร์ (High Availability)
  selector:
    matchLabels:
      app: refined-backend
  template:
    metadata:
      labels:
        app: refined-backend
    spec:
      containers:
      - name: backend
        image: moondev06/refined-backend:latest # ใช้ชื่อ Image ของคุณ
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer # เพื่อให้ AWS สร้าง Load Balancer ให้เราตามโจทย์
  selector:
    app: refined-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000